name: "Build and deploy"
on:
  # trigger workflow on push event on main branch
  push:
    branches:
      - main
    
    # ignore triggering workflow if there is any changes in below files.
    paths-ignore:
      - README.md
      - LICENSE
      - CONTRIBUTING.md
      - .gitignore
  
  # trigger the workflow on pull requent in main branch
  pull_request:
    branches:
      - main

  # run workspace manually from the actions tab, provide option to force deply
  workflow_dispatch:
    inputs:
      force_deploy:
        type: boolean
        description: "Force deploy"
        default: false
        required: true

# setup permissions
permissions:
  contents: read
  pages: write
  issues: write
  id-token: write

# restrice one deployment at a time, If other runs are queued, cancel the older runs
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  # test job
  # run all the necessary tests
  test:
    runs-on: ubuntu-latest
    env:
      # set environment variable
      env_var: ${{ vars.ENV_CONTEXT_VAR }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # install node js 18
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      # install all the dependencies using cache to speed up the process
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install
      
      - name: Run all the linters
        run: npm run lint:all

      # run scripts
      - name: Run all the scripts
        run: |
          node script/url-checker.js -t ${{ vars.URL_CHECKER_TIMEOUT }}

  # build job
  build:
    runs-on: ubuntu-latest
    
    # make sure this job runs only if the test job is run successfully.
    needs: test

    # setup pages using actions/configure-pages@v4
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      # setup node 18
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # install all dependencides (use cache to speed up)
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Build distribution files
        run:
          # get the repo name by splitting the path prefix
          PATH_PREFIX="/$(echo '${{ github.repository }}' | cut -d'/' -f2-)/"
          npm run prod

      # upload all the contents of the build _site as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site/"
  
  # deploy job
  deploy:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    # restric deploying changes if any of the previous jobs fails
    needs: build
    
    # deploy the site to GitHub pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # report the status of deplyment
      - name: Report status
        run: |
          # authenticate to GitHub with GITHUB_TOKEN
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          # create an issue that reports the status of the deployment
          gh issue create \
            --repo ${{ github.repository }} \
            --title "$(date -u) - Deployment: ${{ steps.deployment.outcome }}" \
            --body "URL: ${{ steps.deployment.outputs.page_url }}"